import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Whisdr App | Search',
  description: 'Generated by create next app',
}

export default function SearchLayout({ children }: { children: React.ReactNode }) {
  return <section className="md:py-18 mx-auto  grow  px-6 py-2 pt-24">{children}</section>
}
