import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import './globals.css'
import { cn } from '@/lib/utils'
import Navbar from '@/components/layout/Navbar'
import Providers from '@/components/providers/Providers'
//TODO: font belerlene fonta gore duzenlenecek
export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})
export const metadata: Metadata = {
  title: 'Whisdr App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn('bg-background min-h-screen font-sans antialiased', fontSans.variable)}>
        <NextTopLoader showSpinner={false} color="#009fb7" height={5} />
        <Providers>
          <Navbar />
          <main className=" mx-auto h-fit grow p-4 ">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
